apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  tier: webserver
resources:
  - deployment.yaml
  - service.yaml
  - role.yaml
  - rolebinding.yaml
  - serviceaccount.yaml
