apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-webserver
  namespace: default
subjects:
- kind: ServiceAccount
  name: airflow-webserver
roleRef:
  kind: Role
  name: airflow-webserver
  apiGroup: rbac.authorization.k8s.io
